// <auto-generated />
using System;
using BancoTempo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BancoTempo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611232631_AumentarLimiteDescricaoHtml")]
    partial class AumentarLimiteDescricaoHtml
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BancoTempo.Api.Models.AnexoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnviadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("EnviadoPorId");

                    b.ToTable("AnexosAtividades");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompradorId")
                        .HasColumnType("integer");

                    b.Property<int>("CustoHoras")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<int?>("DisciplinaId")
                        .HasColumnType("integer");

                    b.Property<string>("FeedbackModeracao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OfertanteId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("OfertanteId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.ChatPrivado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.MensagemChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatPrivadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemetenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatPrivadoId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SaldoHoras")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.AnexoAtividade", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.Atividade", "Atividade")
                        .WithMany("Anexos")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoTempo.Api.Models.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atividade");

                    b.Navigation("EnviadoPor");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Atividade", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.Usuario", "Comprador")
                        .WithMany("AtividadesCompradas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BancoTempo.Api.Models.Disciplina", "Disciplina")
                        .WithMany("Atividades")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BancoTempo.Api.Models.Usuario", "Ofertante")
                        .WithMany("AtividadesOfertadas")
                        .HasForeignKey("OfertanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Disciplina");

                    b.Navigation("Ofertante");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.ChatPrivado", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.Atividade", "Atividade")
                        .WithOne()
                        .HasForeignKey("BancoTempo.Api.Models.ChatPrivado", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Disciplina", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.MensagemChat", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.ChatPrivado", "ChatPrivado")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChatPrivadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoTempo.Api.Models.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatPrivado");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Usuario", b =>
                {
                    b.HasOne("BancoTempo.Api.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Atividade", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.ChatPrivado", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Curso", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Disciplina", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("BancoTempo.Api.Models.Usuario", b =>
                {
                    b.Navigation("AtividadesCompradas");

                    b.Navigation("AtividadesOfertadas");
                });
#pragma warning restore 612, 618
        }
    }
}
